application: rentmanagement-1284
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /.*
  script: rentmanagement.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "latest"
